# Generated by Django 2.0.13 on 2022-06-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20220629_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='称呼')),
                ('content', models.CharField(max_length=240, verbose_name='内容')),
                ('pub_time', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('article', models.ForeignKey(on_delete=None, to='article.Article', verbose_name='博客')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'article_comment',
            },
        ),
    ]
