# Generated by Django 2.0.13 on 2022-07-01 18:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pub_time',
        ),
        migrations.AddField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='评论时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=16, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='uploads/article/2022/06/30/photos2.jpg', upload_to='uploads/article/%Y/%m/%d', verbose_name='文章图片'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='文章'),
        ),
    ]
