# Generated by Django 2.0.13 on 2022-07-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_leavemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemessage',
            name='content',
            field=models.CharField(max_length=240, null=True, verbose_name='内容'),
        ),
    ]
