# Generated by Django 2.0.13 on 2022-07-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20220702_0846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveMessage',
        ),
    ]
